version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    command: bash -c "rabbitmq-plugins enable rabbitmq_delayed_message_exchange && rabbitmq-server"
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  nestjs-app:
    build: ./delay
    volumes:
      - ./delay:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229" 
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development

  nestjs-tests:
    build: ./delay
    volumes:
      - ./delay:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run test:watchAll:debug
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "9230:9230"
    environment:
      - NODE_ENV=test

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password

volumes:
  rabbitmq_data:
  postgres_data:
  minio_data:
