version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    command: bash -c "rabbitmq-plugins enable rabbitmq_delayed_message_exchange && rabbitmq-server"
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nestjs-app:
    build: ./delay
    volumes:
      - ./delay:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229" 
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=development

  nestjs-tests:
    build: ./delay
    volumes:
      - ./delay:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run test:watchAll:debug
    ports:
      - "9230:9230"
    environment:
      - NODE_ENV=test

volumes:
  rabbitmq_data:
